__author__ = 'rich'

TWITTER_CONSUMER_KEY = "7fVQ3PzxbO1BvJDVVnVTA"
TWITTER_CONSUMER_SECRET = "I7t4mD9Wm8Otn17XDyj7OPjYnpDxSfJJ5zaKqGOok"

TWITTER_ACCESS_TOKEN = "33349294-H5XiEy4CV5ug9htfvkJlaeUAImeYtMbOduiYWxkwF"
TWITTER_ACCESS_TOKEN_SECRET = "d5VEsIiZzs2qoJCloqsHC0asb6mNNpXON1KAlM7vEis"

AWS_ACCESS_KEY_ID = "AKIAI6VFL7INEO3TVIHQ"
AWS_SECRET_ACCESS_KEY = "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"